"""Email digest for ArXiv Scout — sends top papers via Gmail SMTP."""

import smtplib
import os
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from arxiv_scout.db import Database


def build_digest_html(db: Database, top_n: int = 20) -> str:
    """Build an HTML email digest of the top-scored papers."""
    papers = db.get_papers(min_score=0, order_by="combined_score", limit=top_n)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    rows = []
    for p in papers:
        authors = db.get_paper_authors(p["id"])
        author_parts = []
        for a in authors[:5]:
            affs = db.get_author_affiliations(a["id"])
            matched = [af["matched_keyword"] for af in affs if af["matched_keyword"]]
            name_html = a["name"]
            if matched:
                badges = " ".join(
                    f'<span style="background:#e6f4ea;color:#1e7e34;padding:1px 5px;'
                    f'border-radius:3px;font-size:11px;">{kw}</span>'
                    for kw in set(matched)
                )
                name_html = f"<b>{a['name']}</b> {badges}"
            author_parts.append(name_html)
        if len(authors) > 5:
            author_parts.append(f"+{len(authors) - 5} more")
        authors_html = ", ".join(author_parts)

        score = p["combined_score"] or 0
        if score >= 7:
            badge_color = "#28a745"
        elif score >= 4:
            badge_color = "#ffc107"
        else:
            badge_color = "#6c757d"

        summary_html = ""
        if p["llm_summary"]:
            summary_html = (
                f'<div style="margin-top:6px;padding:8px;background:#f8f9fa;'
                f'border-left:3px solid #28a745;font-size:13px;">'
                f'<b>AI:</b> {p["llm_summary"]}</div>'
            )

        abstract_snippet = (p["abstract"] or "")[:200]
        if len(p["abstract"] or "") > 200:
            abstract_snippet += "..."

        rows.append(f"""
        <tr>
            <td style="padding:12px;border-bottom:1px solid #eee;">
                <div style="display:flex;gap:10px;">
                    <span style="background:{badge_color};color:white;padding:4px 10px;
                        border-radius:6px;font-weight:bold;font-size:16px;min-width:40px;
                        text-align:center;">{score:.1f}</span>
                    <div>
                        <a href="{p['arxiv_url']}" style="color:#0366d6;font-size:15px;
                            font-weight:600;text-decoration:none;">{p['title']}</a>
                        <div style="color:#586069;font-size:12px;margin-top:2px;">
                            {p['categories']} &middot; {p['published_date']}
                            &middot; H={p['heuristic_score']:.1f}
                            {f" L={p['llm_score']:.0f}" if p['llm_score'] else ""}
                        </div>
                        <div style="font-size:13px;margin-top:4px;">{authors_html}</div>
                        <div style="font-size:12px;color:#586069;margin-top:4px;">
                            {abstract_snippet}
                        </div>
                        {summary_html}
                    </div>
                </div>
            </td>
        </tr>
        """)

    paper_count = db.execute("SELECT COUNT(*) as c FROM papers").fetchone()["c"]
    llm_count = db.execute(
        "SELECT COUNT(*) as c FROM papers WHERE llm_score IS NOT NULL AND DATE(scored_at) = DATE('now')"
    ).fetchone()["c"]

    return f"""
    <html>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
        max-width:700px;margin:0 auto;color:#24292e;">
        <div style="background:#24292e;color:white;padding:16px 20px;border-radius:8px 8px 0 0;">
            <h1 style="margin:0;font-size:20px;">ArXiv Scout Daily Digest</h1>
            <p style="margin:4px 0 0;color:#8b949e;font-size:13px;">
                {today} &middot; {paper_count} papers tracked &middot; {len(papers)} top results
            </p>
        </div>
        <table style="width:100%;border-collapse:collapse;">
            {"".join(rows)}
        </table>
        <div style="padding:16px;text-align:center;color:#8b949e;font-size:12px;
            border-top:1px solid #eee;">
            Generated by ArXiv Scout &middot; hep-ph &amp; cs.LG
        </div>
    </body>
    </html>
    """


def send_email(subject: str, html_body: str, smtp_config: dict) -> None:
    """Send an HTML email via SMTP."""
    sender = smtp_config["sender"]
    recipient = smtp_config.get("recipient", sender)
    password = smtp_config["password"]
    host = smtp_config.get("host", "smtp.gmail.com")
    port = smtp_config.get("port", 587)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(host, port, timeout=30) as server:
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, [recipient], msg.as_string())


def send_digest(db: Database, config: dict, top_n: int = 20, dry_run: bool = False) -> None:
    """Build and send (or print) the daily digest."""
    html = build_digest_html(db, top_n=top_n)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"ArXiv Scout Digest — {today}"

    if dry_run:
        print(html)
        print(f"\n--- Subject: {subject} ---")
        print("(dry run — email not sent)")
        return

    smtp_config = {
        "sender": os.environ.get("SMTP_EMAIL", config.get("email", {}).get("sender", "")),
        "recipient": os.environ.get("SMTP_RECIPIENT", config.get("email", {}).get("recipient", "")),
        "password": os.environ.get("SMTP_PASSWORD", config.get("email", {}).get("password", "")),
        "host": config.get("email", {}).get("host", "smtp.gmail.com"),
        "port": config.get("email", {}).get("port", 587),
    }

    if not smtp_config["sender"] or not smtp_config["password"]:
        print("Error: SMTP_EMAIL and SMTP_PASSWORD must be set in .env or config.yaml")
        print("For Gmail: create an App Password at https://myaccount.google.com/apppasswords")
        return

    if not smtp_config["recipient"]:
        smtp_config["recipient"] = smtp_config["sender"]

    send_email(subject, html, smtp_config)
    print(f"Digest sent to {smtp_config['recipient']}")
